name: Deploy Application

on:
  push:
    branches: 
      - master

job:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile Css and Javascript
        run:  |
          npm install
          npm run prod

      - name: configure php 8.0
